name: Build and Publish

on: 
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: buderus-km271_en.yaml
      name: KM271-WiFi
